Сделал первую задачу.
js-tasks-ru/jsbasic-20230116-2_mikhail-ivichev pull request #1
Opened 2023-01-17 19:45 UTC by Mivich

2023-01-17 19:45 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2023-01-18 16:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-18 16:38 UTC, SinimaWath requested changes

2023-01-18 16:38 UTC, SinimaWath commented on 0-module/1-task/index.js
> +calcSum();
В файле надо оставить только одно решение: `function sum`, давай эту функцию уберем

2023-01-18 16:38 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  console.log(result);
Функция в качестве результат, должна возвращать сумму. Для этого используется return:
`return m + n;`

2023-01-20 12:44 UTC, SinimaWath approved these changes

2023-01-20 12:44 UTC, merged